#!/usr/bin/env python3
"""RDODI OE-Assessor v1.2.0 — four-gate ontology-quality assessor (C1, next iteration).

Adds over v1.0.0:
  - Gate 1 upgraded to FULL OWL-DL consistency via HermiT (owlready2), with OWL-RL fallback.
  - Gate 2 takes an applicable domain-shapes graph.
  - Gate 4 extended: ClassRichness, AverageBreadth, TaxonomicRichness, Cohesion (+ AR/RR/IR/AnnR), and
    explicit FAIR indicators (F/A/I/R) — all a COMPUTED SUBSET of / aligned to the OE quality model,
    NOT a claim of full OQuaRE/OntoQA/FAIR certification (L-66).
  - Closed loop: assess -> auto-apply ONLY non-fabricating fixes (metadata completeness) -> re-assess.
    It REFUSES to auto-fix provenance/source/substance gaps (those require human judgment; auto-filling
    them would fabricate — the anti-pattern this project exists to prevent).

Usage: python3 rdodi_oe_assessor_v1_1_0.py <ontology.ttl> [domain_shapes.ttl]
"""
import sys, re, tempfile, rdflib
from rdflib import RDF, RDFS, OWL, Namespace, URIRef, Literal
from rdflib.namespace import SKOS, DCTERMS
DCT = DCTERMS
STAMP = re.compile(r'generated by|generator v\d|rdodi (generator|pipeline) v|render_out|auto-generated', re.I)

def _g(p):
    g = rdflib.Graph(); g.parse(p, format="turtle"); return g

# ---------------- Gate 1: FULL OWL-DL consistency (HermiT), OWL-RL fallback ----------------
def gate_consistency(g):
    try:
        import owlready2
        tf = tempfile.NamedTemporaryFile(suffix=".owl", delete=False)
        g.serialize(destination=tf.name, format="xml")
        w = owlready2.World(); onto = w.get_ontology("file://" + tf.name).load()
        try:
            with onto:
                owlready2.sync_reasoner(w, debug=0)
            inc = list(w.inconsistent_classes())
            verdict = "PASS" if not inc else "FAIL"
            rec = [] if not inc else [f"resolve unsatisfiable class {c.name}" for c in inc[:5]]
            return {"gate": "consistency", "profile": "OWL-DL (HermiT)", "verdict": verdict,
                    "detail": f"{len(inc)} unsatisfiable classes", "recommend": rec}
        except owlready2.OwlReadyInconsistentOntologyError:
            return {"gate": "consistency", "profile": "OWL-DL (HermiT)", "verdict": "FAIL",
                    "detail": "ontology globally inconsistent", "recommend": ["repair contradictory axioms"]}
    except Exception as e:
        # honest fallback
        import owlrl
        gc = rdflib.Graph(); [gc.add(t) for t in g]
        owlrl.DeductiveClosure(owlrl.OWLRL_Semantics).expand(gc)
        unsat = [s for s, _, o in gc.triples((None, RDFS.subClassOf, OWL.Nothing)) if s != OWL.Nothing]
        return {"gate": "consistency", "profile": f"OWL-RL fallback ({str(e)[:40]})",
                "verdict": "PASS" if not unsat else "FAIL", "detail": f"{len(unsat)} unsatisfiable (RL)", "recommend": []}

# ---------------- Gate 2: SHACL against an applicable domain-shapes graph ----------------
def gate_shacl(g, shapes_path):
    if not shapes_path:
        return {"gate": "shacl", "verdict": "SKIPPED", "detail": "no domain-shapes graph provided", "recommend": []}
    import pyshacl
    SH = Namespace("http://www.w3.org/ns/shacl#")
    conforms, rg, _ = pyshacl.validate(g, shacl_graph=shapes_path, inference="rdfs", advanced=True)
    res = list(rg.subjects(RDF.type, SH.ValidationResult))
    viol = sum(1 for r in res if rg.value(r, SH.resultSeverity) == SH.Violation)
    warn = sum(1 for r in res if rg.value(r, SH.resultSeverity) == SH.Warning)
    return {"gate": "shacl", "verdict": "PASS" if viol == 0 else "FAIL",
            "detail": f"{viol} Violations, {warn} Warnings (advisory)",
            "recommend": [] if viol == 0 else ["fix Violation-severity results"]}

# ---------------- Gate 3: verbatim fidelity ----------------
def gate_fidelity(g):
    defined = list(g.subjects(SKOS.definition, None))
    bad = [c for c in defined if (g.value(c, DCT.source) is None or STAMP.search(str(g.value(c, DCT.source))))]
    return {"gate": "fidelity", "verdict": "PASS" if not bad else "FAIL",
            "detail": f"{len(defined)-len(bad)}/{len(defined)} defined entities real-sourced",
            "recommend": ([] if not bad else [f"{len(bad)} entities lack a real source — HUMAN must supply (no auto-fill)"]),
            "human_only": True}

# ---------------- Gate 4: OE quality metrics (extended) + FAIR indicators ----------------
def gate_quality_metrics(g):
    """OQuaRE base metrics + OntoQA metrics + FAIR indicators, COMPUTED per published definitions
    (Duque-Ramos et al. OQuaRE; Tartir et al. OntoQA; Wilkinson et al. FAIR). These are COMPUTED metrics,
    NOT third-party certification, and NOT the full ISO-25000 characteristic aggregation (that is a noted
    next layer). Labelled per L-66."""
    from collections import defaultdict
    cl = set(c for c in g.subjects(RDF.type, OWL.Class) if isinstance(c, URIRef))
    C = len(cl) or 1
    sub = [(s,o) for s,_,o in g.triples((None,RDFS.subClassOf,None)) if s in cl and isinstance(o,URIRef) and o in cl]
    H = len(sub)
    objp = set(g.subjects(RDF.type, OWL.ObjectProperty)); P = len(objp)
    dtp = set(g.subjects(RDF.type, OWL.DatatypeProperty)); att = len(dtp)
    ann = sum(1 for c in cl if g.value(c,SKOS.definition) or g.value(c,RDFS.comment))
    parents = defaultdict(list); children = defaultdict(list)
    for c,o in sub: parents[c].append(o); children[o].append(c)
    roots = [c for c in cl if c not in parents]
    # depth via memoised longest path to a root
    depthmemo={}
    def depth(c, seen=None):
        seen=seen or set()
        if c in seen: return 0
        if c in depthmemo: return depthmemo[c]
        if c not in parents: return 1
        d = 1 + max((depth(p, seen|{c}) for p in parents[c]), default=0); depthmemo[c]=d; return d
    depths=[depth(c) for c in cl]
    DITOnto = max(depths) if depths else 0
    NOCOnto = (sum(len(children[c]) for c in children)/len(children)) if children else 0.0
    TMOnto = sum(1 for c in cl if len(parents[c])>1)/C                      # tangledness
    # coupling: distinct classes each class connects to (parents + obj-prop domain/range partners)
    coupled=defaultdict(set)
    for c,o in sub: coupled[c].add(o)
    for prop in objp:
        d=g.value(prop,RDFS.domain); r=g.value(prop,RDFS.range)
        if d in cl and r in cl: coupled[d].add(r)
    CBOOnto = (sum(len(v) for v in coupled.values())/C)
    RROnto = (P/(H+P)) if (H+P) else 0.0
    AROnto = att/C
    INROnto = H/C
    ANOnto = ann/C
    WMCOnto = (P+att)/C                                                     # avg properties per class
    NOMOnto = P/C
    LCOMOnto = (sum(depths)/len(depths)) if depths else 0.0                 # avg depth (path to root proxy)
    oquare = {"ANOnto":ANOnto,"AROnto":AROnto,"INROnto":INROnto,"RROnto":RROnto,"CBOOnto":CBOOnto,
              "DITOnto":DITOnto,"NOCOnto":NOCOnto,"WMCOnto":WMCOnto,"NOMOnto":NOMOnto,
              "LCOMOnto":LCOMOnto,"TMOnto":TMOnto}
    # OntoQA: schema (above) + KB metrics when an ABox is present
    inds = set(s for s,_,o in g.triples((None,RDF.type,None)) if o in cl)
    populated = set(o for _,_,o in g.triples((None,RDF.type,None)) if o in cl)
    ontoqa = {"SchemaRelationshipRichness":RROnto, "SchemaInheritanceRichness":INROnto,
              "SchemaAttributeRichness":AROnto,
              "KB_ClassRichness(populated/total)": round(len(populated)/C,3),
              "KB_AveragePopulation": round((len(inds)/C),3) if inds else 0.0}
    # FAIR (real handling incl. R license/provenance)
    ont = next(iter(g.subjects(RDF.type, OWL.Ontology)), None)
    DC = Namespace("http://purl.org/dc/elements/1.1/")
    has_license = bool(ont and (g.value(ont,DCT.license) or g.value(ont,DC.rights) or g.value(ont,URIRef("http://purl.org/dc/terms/rights"))))
    has_prov = bool(ont and g.value(ont,DCT.source)) or any(g.value(c,DCT.source) for c in list(cl)[:50])
    fair = {"F_versionIRI":bool(ont and g.value(ont,OWL.versionIRI)),
            "F_rich_metadata": bool(ont and len(list(g.predicate_objects(ont)))>=4),
            "A_http_iris": all(str(c).startswith("http") for c in list(cl)[:50]),
            "I_standard_vocab": any(p in set(g.predicates()) for p in [SKOS.definition,DCT.source,RDFS.label]),
            "R_license": has_license, "R_provenance": has_prov,
            "R_versioning": bool(ont and g.value(ont,OWL.versionInfo))}
    recs=[]
    floors={"RROnto":0.30,"ANOnto":0.80,"INROnto":0.50}
    for n,f in floors.items():
        if oquare[n]<f: recs.append(f"OQuaRE {n} {oquare[n]:.2f} < floor {f:.2f}")
    recs += [f"FAIR-{k} absent" for k,v in fair.items() if not v]
    verdict = "PASS" if not recs else "ADVISORY"
    return {"gate":"OQuaRE+OntoQA+FAIR (COMPUTED per published defs; not certification; ISO-25000 aggregation = next layer)",
            "verdict":verdict,
            "detail":{"OQuaRE":{k:round(v,3) for k,v in oquare.items()},"OntoQA":ontoqa,"FAIR":fair},
            "recommend":recs}

def assess(ontology_path, shapes_path=None, _quiet=False):
    g = _g(ontology_path)
    gates = [gate_consistency(g), gate_shacl(g, shapes_path), gate_fidelity(g), gate_quality_metrics(g)]
    hard = [x for x in gates if x["verdict"] == "FAIL"]
    overall = "ACCEPT" if not hard else "REJECT (enhance -> re-assess)"
    if not _quiet:
        print(f"=== OE-Assessor v1.2.0 on {ontology_path} ===")
        for x in gates:
            extra = f" [{x.get('profile')}]" if x.get("profile") else ""
            print(f"[{x['verdict']:8s}] {x['gate']}{extra}: {x['detail']}")
            for r in x["recommend"]:
                print(f"           ↳ {r}")
        print(f"OVERALL: {overall}")
    return overall, gates, g

# ---------------- Closed loop: auto-fix ONLY non-fabricating metadata, then re-assess ----------------
def enhance_safe(g, gates):
    """Apply ONLY deterministic, non-fabricating fixes. NEVER touches source/provenance/substance."""
    applied = []
    ont = next(iter(g.subjects(RDF.type, OWL.Ontology)), None)
    if ont:
        vinfo = g.value(ont, OWL.versionInfo)
        if vinfo and not g.value(ont, OWL.versionIRI):
            # versionIRI is the STANDARD form of the already-declared version — derivation, not fabrication
            g.add((ont, OWL.versionIRI, URIRef(f"{str(ont)}/{str(vinfo)}")))
            applied.append(f"derived owl:versionIRI from existing owl:versionInfo '{vinfo}' (FAIR-F)")
    return applied

def closed_loop(ontology_path, shapes_path=None):
    print("--- PASS 1: assess ---")
    ov1, gates, g = assess(ontology_path, shapes_path)
    applied = enhance_safe(g, gates)
    print(f"\n--- ENHANCE (safe, non-fabricating only): {len(applied)} fix(es) ---")
    for a in applied: print("   +", a)
    print("   (REFUSED to auto-fix: fidelity/source gaps — routed to human, never auto-filled)")
    tmp = tempfile.NamedTemporaryFile(suffix=".ttl", delete=False); g.serialize(destination=tmp.name, format="turtle")
    print("\n--- PASS 2: re-assess ---")
    ov2, gates2, _ = assess(tmp.name, shapes_path)
    return ov1, ov2

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__); raise SystemExit(2)
    shapes = sys.argv[2] if len(sys.argv) > 2 else None
    if "--loop" in sys.argv:
        closed_loop(sys.argv[1], shapes if shapes != "--loop" else None)
    else:
        ov, _, _ = assess(sys.argv[1], shapes)
        sys.exit(0 if ov == "ACCEPT" else 1)
