#!/usr/bin/env python3
"""RDODI OE-Assessor v1.0.0 — the four-gate ontology-quality assessor (reassessed-plan C1).

Principle: probabilistic proposes, deterministic disposes. Runs four deterministic gates on a domain
ontology and emits an assess -> enhance -> re-assess verdict with tier-C enhancement recommendations.

Honest labelling (L-65/L-66):
  - Gate 1 is OWL-RL profile consistency (owlrl). It is NOT full OWL-DL: owlready2/HermiT is absent in
    this environment. Upgrade path noted in the report.
  - Gate 4 metrics are computed per the OE Pack quality model's OWN formulas
    (quality_tbox v5.14.0: AttributeRichness AR=|att|/|C|, RelationshipRichness RR=|P|/(|H|+|P|),
    InheritanceRichness IR=|H|/|C|, ClassRichness, AnnotationRichness). They are a COMPUTED SUBSET of that
    model, referenced as the authority — NOT a claim of full OQuaRE/OntoQA/FAIR compliance.

Usage: python3 rdodi_oe_assessor_v1_0_0.py <ontology.ttl> [shapes.ttl]
"""
import sys, re, rdflib
from rdflib import RDF, RDFS, OWL
from rdflib.namespace import SKOS, DCTERMS

DCT = DCTERMS
STAMP = re.compile(r'generated by|generator v\d|rdodi (generator|pipeline) v|render_out|auto-generated', re.I)

def _g(path):
    g = rdflib.Graph(); g.parse(path, format="turtle"); return g

# ---------------- Gate 1: consistency (OWL-RL profile) ----------------
def gate_consistency(g):
    import owlrl
    gc = rdflib.Graph(); [gc.add(t) for t in g]
    try:
        owlrl.DeductiveClosure(owlrl.OWLRL_Semantics).expand(gc)
    except Exception as e:
        return {"gate": "consistency", "profile": "OWL-RL", "verdict": "FAIL",
                "detail": f"reasoner error: {e}", "recommend": ["inspect axioms that crash RL closure"]}
    unsat = [s for s, _, o in gc.triples((None, RDFS.subClassOf, OWL.Nothing)) if s != OWL.Nothing]
    verdict = "PASS" if not unsat else "FAIL"
    rec = [] if not unsat else [f"resolve unsatisfiable class {str(c).split('#')[-1]}" for c in unsat[:5]]
    return {"gate": "consistency", "profile": "OWL-RL (not full OWL-DL: owlready2 absent)",
            "verdict": verdict, "detail": f"{len(unsat)} unsatisfiable classes", "recommend": rec}

# ---------------- Gate 2: SHACL conformance ----------------
def gate_shacl(g, shapes_path):
    if not shapes_path:
        return {"gate": "shacl", "verdict": "SKIPPED", "detail": "no shapes graph provided", "recommend": []}
    import pyshacl
    SH = rdflib.Namespace("http://www.w3.org/ns/shacl#")
    conforms, rg, _ = pyshacl.validate(g, shacl_graph=shapes_path, inference="rdfs", advanced=True)
    res = list(rg.subjects(RDF.type, SH.ValidationResult))
    viol = sum(1 for r in res if rg.value(r, SH.resultSeverity) == SH.Violation)
    warn = sum(1 for r in res if rg.value(r, SH.resultSeverity) == SH.Warning)
    verdict = "PASS" if viol == 0 else "FAIL"   # L-66: Warnings advisory
    return {"gate": "shacl", "verdict": verdict, "detail": f"{viol} Violations, {warn} Warnings (advisory)",
            "recommend": [] if viol == 0 else ["fix Violation-severity SHACL results"]}

# ---------------- Gate 3: verbatim fidelity (real sourcing of definitions) ----------------
def gate_fidelity(g):
    defined = [c for c in g.subjects(SKOS.definition, None)]
    bad = [c for c in defined if (g.value(c, DCT.source) is None or STAMP.search(str(g.value(c, DCT.source))))]
    verdict = "PASS" if not bad else "FAIL"
    rec = [] if not bad else [f"{len(bad)} defined entities lack a real (non-stamp) source"]
    return {"gate": "fidelity", "verdict": verdict,
            "detail": f"{len(defined)-len(bad)}/{len(defined)} defined entities carry a real source",
            "recommend": rec}

# ---------------- Gate 4: OE quality metrics (computed per OE quality_tbox formulas) ----------------
def gate_quality_metrics(g):
    classes = set(c for c in g.subjects(RDF.type, OWL.Class) if isinstance(c, rdflib.URIRef))
    C = len(classes) or 1
    H = sum(1 for s, _, o in g.triples((None, RDFS.subClassOf, None))
            if s in classes and isinstance(o, rdflib.URIRef) and o in classes)
    P = len(set(g.subjects(RDF.type, OWL.ObjectProperty)))
    att = len(set(g.subjects(RDF.type, OWL.DatatypeProperty)))
    annotated = sum(1 for c in classes if g.value(c, SKOS.definition) or g.value(c, RDFS.comment))
    AR = att / C
    RR = (P / (H + P)) if (H + P) else 0.0
    IR = H / C
    AnnR = annotated / C
    # advisory thresholds (configurable defaults; NOT framework-mandated values)
    th = {"AttributeRichness": (AR, 0.20), "RelationshipRichness": (RR, 0.30),
          "InheritanceRichness": (IR, 0.50), "AnnotationRichness": (AnnR, 0.80)}
    recs = []
    for name, (val, floor) in th.items():
        if val < floor:
            recs.append(f"{name} {val:.2f} < advisory floor {floor:.2f} — enrich the schema accordingly")
    verdict = "PASS" if not recs else "ADVISORY"
    return {"gate": "oe_quality_metrics(subset of OE quality_tbox v5.14.0)", "verdict": verdict,
            "detail": {"|C|": C, "|H|": H, "|P|": P, "|att|": att,
                       "AR": round(AR, 3), "RR": round(RR, 3), "IR": round(IR, 3), "AnnR": round(AnnR, 3)},
            "recommend": recs}

def assess(ontology_path, shapes_path=None):
    g = _g(ontology_path)
    gates = [gate_consistency(g), gate_shacl(g, shapes_path), gate_fidelity(g), gate_quality_metrics(g)]
    hard = [x for x in gates if x["verdict"] == "FAIL"]
    overall = "ACCEPT" if not hard else "REJECT (enhance -> re-assess)"
    print(f"=== RDODI OE-Assessor v1.0.0 on {ontology_path} ===")
    for x in gates:
        print(f"[{x['verdict']:8s}] {x['gate']}: {x['detail']}")
        for r in x["recommend"]:
            print(f"           ↳ enhance: {r}")
    print(f"OVERALL: {overall}")
    return overall, gates

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__); raise SystemExit(2)
    ov, _ = assess(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else None)
    sys.exit(0 if ov == "ACCEPT" else 1)
