#!/usr/bin/env python3
"""RDODI Source-Type-Aware Fidelity Gate v2.0.0 (R-E1).

Discovery from the STG study: the v1 fidelity gate required a LITERATURE source on every defined entity, which
wrongly REJECTS normative/governance vocabulary (whose source is a governing AUTHORITY, not a paper). This gate
distinguishes the two — WITHOUT becoming a loophole.

ANTI-LOOPHOLE INVARIANT: no entity passes with zero sourcing.
  - domain-concept  passes ONLY with a real (non-stamp) literature dcterms:source.
  - normative-term  passes ONLY with a valid authority cite (dct:conformsTo / stg:referencesAuthority /
                    prov:wasInformedBy / fidelity:authoritySource pointing to a non-empty authority IRI).
  - an entity with NEITHER FAILS, regardless of type. Declaring something "normative" does NOT exempt it.

Usage: python3 rdodi_fidelity_gate_v2_0_0.py <ontology.ttl>
"""
import sys, re, rdflib
from rdflib import URIRef
from rdflib.namespace import SKOS, DCTERMS
DCT = DCTERMS
STAMP = re.compile(r'generated by|generator v\d|rdodi (generator|pipeline) v|render_out|auto-generated', re.I)
AUTH_PREDS = [
    DCT.conformsTo,
    URIRef("http://example.org/stg/governance#referencesAuthority"),
    URIRef("http://www.w3.org/ns/prov#wasInformedBy"),
    URIRef("http://example.org/rdodi/fidelity#authoritySource"),
]

def valid_literature(g, c):
    s = g.value(c, DCT.source)
    return bool(s) and isinstance(s, rdflib.Literal) and not STAMP.search(str(s))

def valid_authority(g, c):
    for p in AUTH_PREDS:
        v = g.value(c, p)
        if v is not None and isinstance(v, URIRef) and str(v).strip():
            return True
    # also allow dcterms:source that is an IRI to an authority (not a literal)
    s = g.value(c, DCT.source)
    if s is not None and isinstance(s, URIRef) and str(s).strip():
        return True
    return False

def check(path):
    g = rdflib.Graph(); g.parse(path, format="turtle")
    defined = list(g.subjects(SKOS.definition, None))
    domain_ok = normative_ok = unsourced = 0
    failures = []
    for c in defined:
        lit = valid_literature(g, c)
        auth = valid_authority(g, c)
        if lit:
            domain_ok += 1            # domain-concept, literature-sourced
        elif auth:
            normative_ok += 1         # normative-term, authority-sourced
        else:
            unsourced += 1            # NEITHER -> fail (anti-loophole)
            failures.append(str(c).split('#')[-1])
    verdict = "PASS" if unsourced == 0 else "FAIL"
    total = len(defined)
    print(f"=== Source-Type-Aware Fidelity : {verdict} ===")
    print(f" defined entities: {total}")
    print(f"   domain-concepts (literature-sourced): {domain_ok}")
    print(f"   normative-terms (authority-sourced):  {normative_ok}")
    print(f"   UNSOURCED (neither -> FAIL):           {unsourced}" + (f"  {failures[:8]}" if failures else ""))
    print(" invariant: no entity passes with zero sourcing; declaring 'normative' does not exempt it (no loophole).")
    return verdict, {"total": total, "domain_ok": domain_ok, "normative_ok": normative_ok, "unsourced": unsourced}

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__); raise SystemExit(2)
    v, _ = check(sys.argv[1])
    sys.exit(0 if v == "PASS" else 1)
