#!/usr/bin/env python3
"""RDODI OE-Assessor v1.1.0 — four-gate ontology-quality assessor (C1, next iteration).

Adds over v1.0.0:
  - Gate 1 upgraded to FULL OWL-DL consistency via HermiT (owlready2), with OWL-RL fallback.
  - Gate 2 takes an applicable domain-shapes graph.
  - Gate 4 extended: ClassRichness, AverageBreadth, TaxonomicRichness, Cohesion (+ AR/RR/IR/AnnR), and
    explicit FAIR indicators (F/A/I/R) — all a COMPUTED SUBSET of / aligned to the OE quality model,
    NOT a claim of full OQuaRE/OntoQA/FAIR certification (L-66).
  - Closed loop: assess -> auto-apply ONLY non-fabricating fixes (metadata completeness) -> re-assess.
    It REFUSES to auto-fix provenance/source/substance gaps (those require human judgment; auto-filling
    them would fabricate — the anti-pattern this project exists to prevent).

Usage: python3 rdodi_oe_assessor_v1_1_0.py <ontology.ttl> [domain_shapes.ttl]
"""
import sys, re, tempfile, rdflib
from rdflib import RDF, RDFS, OWL, Namespace, URIRef, Literal
from rdflib.namespace import SKOS, DCTERMS
DCT = DCTERMS
STAMP = re.compile(r'generated by|generator v\d|rdodi (generator|pipeline) v|render_out|auto-generated', re.I)

def _g(p):
    g = rdflib.Graph(); g.parse(p, format="turtle"); return g

# ---------------- Gate 1: FULL OWL-DL consistency (HermiT), OWL-RL fallback ----------------
def gate_consistency(g):
    try:
        import owlready2
        tf = tempfile.NamedTemporaryFile(suffix=".owl", delete=False)
        g.serialize(destination=tf.name, format="xml")
        w = owlready2.World(); onto = w.get_ontology("file://" + tf.name).load()
        try:
            with onto:
                owlready2.sync_reasoner(w, debug=0)
            inc = list(w.inconsistent_classes())
            verdict = "PASS" if not inc else "FAIL"
            rec = [] if not inc else [f"resolve unsatisfiable class {c.name}" for c in inc[:5]]
            return {"gate": "consistency", "profile": "OWL-DL (HermiT)", "verdict": verdict,
                    "detail": f"{len(inc)} unsatisfiable classes", "recommend": rec}
        except owlready2.OwlReadyInconsistentOntologyError:
            return {"gate": "consistency", "profile": "OWL-DL (HermiT)", "verdict": "FAIL",
                    "detail": "ontology globally inconsistent", "recommend": ["repair contradictory axioms"]}
    except Exception as e:
        # honest fallback
        import owlrl
        gc = rdflib.Graph(); [gc.add(t) for t in g]
        owlrl.DeductiveClosure(owlrl.OWLRL_Semantics).expand(gc)
        unsat = [s for s, _, o in gc.triples((None, RDFS.subClassOf, OWL.Nothing)) if s != OWL.Nothing]
        return {"gate": "consistency", "profile": f"OWL-RL fallback ({str(e)[:40]})",
                "verdict": "PASS" if not unsat else "FAIL", "detail": f"{len(unsat)} unsatisfiable (RL)", "recommend": []}

# ---------------- Gate 2: SHACL against an applicable domain-shapes graph ----------------
def gate_shacl(g, shapes_path):
    if not shapes_path:
        return {"gate": "shacl", "verdict": "SKIPPED", "detail": "no domain-shapes graph provided", "recommend": []}
    import pyshacl
    SH = Namespace("http://www.w3.org/ns/shacl#")
    conforms, rg, _ = pyshacl.validate(g, shacl_graph=shapes_path, inference="rdfs", advanced=True)
    res = list(rg.subjects(RDF.type, SH.ValidationResult))
    viol = sum(1 for r in res if rg.value(r, SH.resultSeverity) == SH.Violation)
    warn = sum(1 for r in res if rg.value(r, SH.resultSeverity) == SH.Warning)
    return {"gate": "shacl", "verdict": "PASS" if viol == 0 else "FAIL",
            "detail": f"{viol} Violations, {warn} Warnings (advisory)",
            "recommend": [] if viol == 0 else ["fix Violation-severity results"]}

# ---------------- Gate 3: verbatim fidelity ----------------
def gate_fidelity(g):
    defined = list(g.subjects(SKOS.definition, None))
    bad = [c for c in defined if (g.value(c, DCT.source) is None or STAMP.search(str(g.value(c, DCT.source))))]
    return {"gate": "fidelity", "verdict": "PASS" if not bad else "FAIL",
            "detail": f"{len(defined)-len(bad)}/{len(defined)} defined entities real-sourced",
            "recommend": ([] if not bad else [f"{len(bad)} entities lack a real source — HUMAN must supply (no auto-fill)"]),
            "human_only": True}

# ---------------- Gate 4: OE quality metrics (extended) + FAIR indicators ----------------
def gate_quality_metrics(g):
    classes = set(c for c in g.subjects(RDF.type, OWL.Class) if isinstance(c, URIRef))
    C = len(classes) or 1
    subedges = [(s, o) for s, _, o in g.triples((None, RDFS.subClassOf, None))
                if s in classes and isinstance(o, URIRef) and o in classes]
    H = len(subedges)
    P = len(set(g.subjects(RDF.type, OWL.ObjectProperty)))
    att = len(set(g.subjects(RDF.type, OWL.DatatypeProperty)))
    annotated = sum(1 for c in classes if g.value(c, SKOS.definition) or g.value(c, RDFS.comment))
    # children map for breadth/leaves
    from collections import defaultdict
    children = defaultdict(list)
    for s, o in subedges: children[o].append(s)
    leaves = sum(1 for c in classes if c not in children)
    nonleaf = [c for c in classes if c in children]
    avg_breadth = (sum(len(children[c]) for c in nonleaf) / len(nonleaf)) if nonleaf else 0.0
    AR = att / C; RR = (P / (H + P)) if (H + P) else 0.0; IR = H / C; AnnR = annotated / C
    ClassRichness = leaves / C                                   # OntoQA-style class richness proxy
    TaxonomicRichness = H / C
    Cohesion = (H + P) / C                                       # connectivity per class (proxy)
    metrics = {"AttributeRichness": AR, "RelationshipRichness": RR, "InheritanceRichness": IR,
               "AnnotationRichness": AnnR, "ClassRichness": ClassRichness, "AverageBreadth": avg_breadth,
               "TaxonomicRichness": TaxonomicRichness, "Cohesion": Cohesion}
    floors = {"RelationshipRichness": 0.30, "AnnotationRichness": 0.80, "InheritanceRichness": 0.50}
    recs = [f"{n} {metrics[n]:.2f} < floor {f:.2f}" for n, f in floors.items() if metrics[n] < f]
    # FAIR indicators (computed subset, labelled)
    ont = next(iter(g.subjects(RDF.type, OWL.Ontology)), None)
    F = bool(ont and g.value(ont, OWL.versionIRI))
    A = all(str(c).startswith("http") for c in list(classes)[:50])
    I = any(p in set(g.predicates()) for p in [SKOS.definition, DCT.source, RDFS.label])
    R = bool(ont and (g.value(ont, DCT.license) or g.value(ont, DCT.source)))
    fair = {"F_versionIRI": F, "A_http_iris": A, "I_standard_vocab": I, "R_license_or_provenance": R}
    fair_recs = [f"FAIR-{k} absent" for k, v in fair.items() if not v]
    return {"gate": "oe_quality_metrics+FAIR (computed subset of OE quality_tbox v5.14.0; NOT full OQuaRE/OntoQA/FAIR)",
            "verdict": "PASS" if not (recs or fair_recs) else "ADVISORY",
            "detail": {**{k: round(v, 3) for k, v in metrics.items()}, "FAIR": fair},
            "recommend": recs + fair_recs}

def assess(ontology_path, shapes_path=None, _quiet=False):
    g = _g(ontology_path)
    gates = [gate_consistency(g), gate_shacl(g, shapes_path), gate_fidelity(g), gate_quality_metrics(g)]
    hard = [x for x in gates if x["verdict"] == "FAIL"]
    overall = "ACCEPT" if not hard else "REJECT (enhance -> re-assess)"
    if not _quiet:
        print(f"=== OE-Assessor v1.1.0 on {ontology_path} ===")
        for x in gates:
            extra = f" [{x.get('profile')}]" if x.get("profile") else ""
            print(f"[{x['verdict']:8s}] {x['gate']}{extra}: {x['detail']}")
            for r in x["recommend"]:
                print(f"           ↳ {r}")
        print(f"OVERALL: {overall}")
    return overall, gates, g

# ---------------- Closed loop: auto-fix ONLY non-fabricating metadata, then re-assess ----------------
def enhance_safe(g, gates):
    """Apply ONLY deterministic, non-fabricating fixes. NEVER touches source/provenance/substance."""
    applied = []
    ont = next(iter(g.subjects(RDF.type, OWL.Ontology)), None)
    if ont:
        vinfo = g.value(ont, OWL.versionInfo)
        if vinfo and not g.value(ont, OWL.versionIRI):
            # versionIRI is the STANDARD form of the already-declared version — derivation, not fabrication
            g.add((ont, OWL.versionIRI, URIRef(f"{str(ont)}/{str(vinfo)}")))
            applied.append(f"derived owl:versionIRI from existing owl:versionInfo '{vinfo}' (FAIR-F)")
    return applied

def closed_loop(ontology_path, shapes_path=None):
    print("--- PASS 1: assess ---")
    ov1, gates, g = assess(ontology_path, shapes_path)
    applied = enhance_safe(g, gates)
    print(f"\n--- ENHANCE (safe, non-fabricating only): {len(applied)} fix(es) ---")
    for a in applied: print("   +", a)
    print("   (REFUSED to auto-fix: fidelity/source gaps — routed to human, never auto-filled)")
    tmp = tempfile.NamedTemporaryFile(suffix=".ttl", delete=False); g.serialize(destination=tmp.name, format="turtle")
    print("\n--- PASS 2: re-assess ---")
    ov2, gates2, _ = assess(tmp.name, shapes_path)
    return ov1, ov2

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__); raise SystemExit(2)
    shapes = sys.argv[2] if len(sys.argv) > 2 else None
    if "--loop" in sys.argv:
        closed_loop(sys.argv[1], shapes if shapes != "--loop" else None)
    else:
        ov, _, _ = assess(sys.argv[1], shapes)
        sys.exit(0 if ov == "ACCEPT" else 1)
