#!/usr/bin/env python3
"""Source-Validity Gate v1.0.0 — rejects non-source provenance (generator self-stamps) used as content sources.
A dcterms:source must attest a real grounding source, NOT describe the generator that produced the artifact.
Verify-by-running: run on any generated ABox; FAIL if any content individual's source is a generation stamp."""
import sys, re, rdflib
from rdflib.namespace import DCTERMS, SKOS
STAMP = re.compile(r'generated by|generator v\d|rdodi (generator|pipeline) v|render_out|^auto-generated', re.I)
def gate(ttl):
    g = rdflib.Graph(); g.parse(ttl, format="turtle")
    bad, good = [], []
    for s in set(g.subjects(SKOS.definition, None)):       # content-bearing individuals
        src = g.value(s, DCTERMS.source)
        sid = str(s).split('#')[-1]
        if src is None:
            bad.append((sid, "NO_SOURCE")); continue
        if STAMP.search(str(src)):
            bad.append((sid, f"GENERATOR_STAMP: {str(src)[:50]}"))
        else:
            good.append((sid, str(src)[:50]))
    verdict = "PASS" if not bad else "FAIL"
    print(f"[{verdict}] source-validity: {len(good)} real-sourced, {len(bad)} invalid")
    for sid, why in bad[:8]: print(f"    INVALID {sid}: {why}")
    return verdict
if __name__ == "__main__":
    sys.exit(0 if gate(sys.argv[1]) == "PASS" else 1)
